# Generated by Django 6.0.7 on 2026-07-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mata_kuliah', models.CharField(max_length=100)),
                ('nama_dosen', models.CharField(max_length=100)),
                ('nim', models.CharField(max_length=20)),
                ('nama', models.CharField(max_length=100)),
                ('prodi', models.CharField(choices=[('TIF', 'Teknik Informatika'), ('SI', 'Sistem Informasi'), ('IK', 'Ilmu Komputer')], max_length=20)),
                ('no_pc', models.CharField(max_length=10)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
